import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavMenu from "@/components/menu/Menu";
import { ThemeProvider } from "@/components/theme-provider";
import TransformContextProvider from "@/components/canvas/TransformProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased font-sans bg-background min-h-screen",
          inter.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <TransformContextProvider>
            <NavMenu />
            {children}
          </TransformContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
